// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantePOS.context;

#nullable disable

namespace RestaurantePOS.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20250320051449_categories")]
    partial class categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantePOS.Domain.Catalogos.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscuntId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscuntId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Configuration.Configurations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertaCorte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoBackup")
                        .HasColumnType("bit");

                    b.Property<string>("BkpAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CobroDirecto")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailNotificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnviarSMS")
                        .HasColumnType("bit");

                    b.Property<string>("EstablecimientoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpresoraCobros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpresoraCortes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpresoraCuentas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpresoraDomicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImpresoraUnica")
                        .HasColumnType("bit");

                    b.Property<string>("RFC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Configuration.Discunts", b =>
                {
                    b.Property<int>("DiscuntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscuntId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("DiscuntName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcent")
                        .HasPrecision(0)
                        .HasColumnType("int");

                    b.HasKey("DiscuntId");

                    b.ToTable("Discunts");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Users.UserType", b =>
                {
                    b.Property<int>("Id_UserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_UserType"));

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_UserType");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Users.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Id_UserType")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Id_UserType")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Catalogos.Categories", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Configuration.Discunts", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscuntId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Users.Users", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Users.UserType", "UserType")
                        .WithOne()
                        .HasForeignKey("RestaurantePOS.Domain.Users.Users", "Id_UserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
